name: Generate Documentation

on:
  push:
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'
    
    - name: Show dirs
      run: ls -a
    
    - name: Move into Tools
      run: cd Tools
      working-directory: ./Tools
    
    - name: Show dirs
      run: ls -a
    
    - name: Build docs
      run: python doc-gen.py
      
    - name: Add generated files
      run: |
        git add .
        git diff-index --quiet HEAD || git commit -m "Add generated files"
      
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}