name: Generate Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'
    
    - name: Build docs
      run: python Tools/doc-gen.py
      
    - name: Push generated files
      run: |
        git config user.name "Docs Generator"
        git config user.email "ballistic@gmail.com"
        git add Docs/*
        git commit -m "Automated Documentation Generation"
        git push